// <auto-generated />
using System;
using MediaUpload.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaUpload.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701031610_FixDeterministicSeedData")]
    partial class FixDeterministicSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaUpload.Domain.Entities.ApiCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedErp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AuthType")
                        .HasColumnType("integer");

                    b.Property<bool>("CanConfig")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanReadJobs")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpload")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiCredentials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedErp = "",
                            AuthType = 0,
                            CanConfig = true,
                            CanReadJobs = true,
                            CanUpload = true,
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            HashedSecret = "$2a$12$5jSzye5F9/NFOW9NR9U1qOGL0yz.2MKdsRTyeoozkykcrgbkSgRSy",
                            Name = "admin",
                            TokenPrefix = "MediaUpl"
                        });
                });

            modelBuilder.Entity("MediaUpload.Domain.Entities.ErpEndpointConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Target")
                        .IsUnique();

                    b.ToTable("ErpEndpointConfigs");
                });

            modelBuilder.Entity("MediaUpload.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HotReload")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thư mục lưu file upload trên NAS",
                            HotReload = true,
                            Key = "nas.upload_dir",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "/mnt/nas/uploads"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thư mục lưu log",
                            HotReload = true,
                            Key = "nas.logs_dir",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "/mnt/nas/logs"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dung lượng trống tối thiểu (bytes)",
                            HotReload = true,
                            Key = "nas.min_free_space_bytes",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1073741824"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Prefix đường dẫn video gửi lên ERP",
                            HotReload = true,
                            Key = "nas.video_path_prefix",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "/homes/video/uploads/"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Dung lượng tối đa mỗi file (bytes)",
                            HotReload = true,
                            Key = "upload.max_file_size_bytes",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1572864000"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Số file tối đa mỗi request",
                            HotReload = true,
                            Key = "upload.max_files_per_request",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Các đuôi file video được phép",
                            HotReload = true,
                            Key = "upload.allowed_extensions",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ".mp4,.avi,.mov,.mkv,.wmv,.flv"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Chu kỳ worker kiểm tra hàng đợi (giây)",
                            HotReload = true,
                            Key = "worker.tick_interval_seconds",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Số lần retry tối đa trước khi Failed",
                            HotReload = true,
                            Key = "worker.max_retry",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Delay giữa các lần retry (phút)",
                            HotReload = true,
                            Key = "worker.retry_delay_minutes",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Số job chạy song song tối đa",
                            HotReload = true,
                            Key = "worker.max_concurrent",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Cửa sổ rate limit (ms)",
                            HotReload = true,
                            Key = "ratelimit.window_ms",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "900000"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Số request tối đa trong cửa sổ",
                            HotReload = true,
                            Key = "ratelimit.max_requests",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Danh sách origin CORS (phân cách bằng dấu phẩy)",
                            HotReload = true,
                            Key = "cors.allowed_origins",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "http://localhost:5173"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Timezone hiển thị (IANA ID)",
                            HotReload = false,
                            Key = "system.timezone",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Asia/Ho_Chi_Minh"
                        });
                });

            modelBuilder.Entity("MediaUpload.Domain.Entities.TimeWindowConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("TimeWindowConfigs");
                });

            modelBuilder.Entity("MediaUpload.Domain.Entities.UploadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErpTarget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FlowId")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.Property<int>("MaxRetry")
                        .HasColumnType("integer");

                    b.Property<string>("NvktId")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SavedPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("UploadJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
